services:
  postgres:
    image: postgres:15
    container_name: attendance_db
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - attendance_network

  backend:
    build: ./backend
    container_name: attendance_backend
    environment:
      - PORT=3002
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=attendance_db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-2024
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    networks:
      - attendance_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - attendance_network

volumes:
  postgres_data:

networks:
  attendance_network:
    driver: bridge
